#!/bin/bash
python cnn_inv_script.py 
python stack_script_1.py 
python stack_script_2.py 
python stack_script_3.py 
python stack_script_4.py 
python stack_script_5.py 
python stack_script_6.py 
python stack_script_7.py 
python stack_script_8.py 
python stack_script_9.py 
python stack_script_10.py 